feeds:
  - https://huggingface.co/blog/feed.xml
  - https://techcrunch.com/tag/ai/feed/
  - https://www.theverge.com/rss/ai-artificial-intelligence/index.xml
  - https://arstechnica.com/information-technology/feed/
  - https://developer.nvidia.com/blog/feed/
  - https://openai.com/blog/rss.xml
  - https://blog.google/technology/ai/rss/
  - https://www.zdnet.com/topic/artificial-intelligence/rss.xml
  - https://www.bensbites.com/feed
  - https://the-decoder.com/feed/
  - https://github.blog/tag/ai/feed/
  - https://blogs.microsoft.com/ai/feed/
  - https://thesequence.substack.com/feed
  - https://www.reddit.com/r/MachineLearning/.rss
