feeds:
  - https://huggingface.co/blog/feed.xml
  - https://techcrunch.com/tag/ai/feed/
  - https://www.theverge.com/rss/ai-artificial-intelligence/index.xml
  - https://arstechnica.com/information-technology/feed/
  - https://blogs.nvidia.com/feed/
  - https://developer.nvidia.com/blog/feed/
  - https://openai.com/blog/rss.xml
  - https://blog.google/technology/ai/rss/
  - https://www.microsoft.com/en-us/research/blog/category/artificial-intelligence/feed/
  - https://syncedreview.com/feed/
  - https://www.zdnet.com/topic/artificial-intelligence/rss.xml